repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.1
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: debug-statements
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
