repos:
-   repo: git://github.com/adambrenecki/pre-commit-python-sorter
    rev: 1.0.5
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.7
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: debug-statements
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
