[tool.poetry]
name = "keithfem_bot"
version = "0.1.0"
description = "A bot for www.keithfem.com telegram group chat that displays the schedule of the radio shows."
authors = ["Lautaro Mazzitelli <lmazzitelli@gmail.com>"]
license = "Attribution-NonCommercial-ShareAlike. CC BY-NC-SA"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
python-telegram-bot = "^13.1"
pytest-cov = "^3.0.0"
cryptography = "^36.0.2"
setuptools = "^65.4.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
freezegun = "^1.2.1"
coveralls = "^3.3.1"
isort = "^5.9.1"
flake8 = "^4.0.1"
black = "^22.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
