[tool.poetry]
name = "keithfem_bot"
version = "0.1.0"
description = "A multipurpose bot for Keithfem."
authors = ["Lautaro Mazzitelli <lmazzitelli@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-telegram-bot = "^12.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
